# Generated by Django 4.1.3 on 2022-12-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('slug', models.SlugField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='meals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
                'db_table': 'meals',
            },
        ),
        migrations.CreateModel(
            name='MealNutrition',
            fields=[
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nutrition', serialize=False, to='dietary_plans.meal')),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('carbs', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meal Nutrition',
                'verbose_name_plural': 'Meal Nutrition Data',
                'db_table': 'meal_nutrition_data',
            },
        ),
        migrations.CreateModel(
            name='DietaryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='dietary_plans')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meals', models.ManyToManyField(blank=True, related_name='plans', to='dietary_plans.meal')),
            ],
            options={
                'verbose_name': 'Dietary Plan',
                'verbose_name_plural': 'Dietary Plans',
                'db_table': 'dietary_plans',
            },
        ),
    ]
