# Generated by Django 4.1.3 on 2022-11-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('slug', models.SlugField(max_length=25)),
                ('description', models.TextField()),
                ('calories', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=1, max_digits=10)),
                ('carbs', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
                'db_table': 'meals',
            },
        ),
        migrations.CreateModel(
            name='DietaryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=25)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meals', models.ManyToManyField(to='dietary_plans.meal')),
            ],
            options={
                'verbose_name': 'Dietary Plan',
                'verbose_name_plural': 'Dietary Plans',
                'db_table': 'dietary_plans',
            },
        ),
    ]
