# Generated by Django 4.1.3 on 2023-01-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietary_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='snippet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='sort',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
