# Generated by Django 4.1.3 on 2022-11-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietary_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dietaryplan',
            name='meals',
            field=models.ManyToManyField(blank=True, to='dietary_plans.meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10),
        ),
    ]
