# Generated by Django 4.1.3 on 2022-11-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietary_plans', '0002_alter_dietaryplan_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
