# Generated by Django 4.1.3 on 2022-11-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietary_plans', '0004_alter_meal_carbs_alter_meal_fat_alter_meal_protein'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealNutrition',
            fields=[
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dietary_plans.meal')),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('carbs', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meal Nutrition',
                'verbose_name_plural': 'Meal Nutrition Data',
                'db_table': 'meal_nutrition_data',
            },
        ),
        migrations.RemoveField(
            model_name='meal',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='protein',
        ),
    ]
