# Generated by Django 4.1.3 on 2022-11-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietary_plans', '0005_mealnutrition_remove_meal_calories_remove_meal_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealnutrition',
            name='meal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nutrition', serialize=False, to='dietary_plans.meal'),
        ),
    ]
