# Generated by Django 4.1.3 on 2022-11-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietary_plans', '0006_alter_mealnutrition_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryplan',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='meals', to='dietary_plans.meal'),
        ),
    ]
