# Generated by Django 4.1.3 on 2022-11-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietary_plans', '0007_alter_dietaryplan_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='img',
            field=models.ImageField(default='', upload_to='meals'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietaryplan',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='plans', to='dietary_plans.meal'),
        ),
    ]
