# Generated by Django 4.1.3 on 2022-12-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietary_plans', '0009_alter_meal_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryplan',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='dietary_plans'),
        ),
    ]
