# Generated by Django 4.1.3 on 2022-12-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0002_pricingplan_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='total_price',
        ),
    ]
