# Generated by Django 4.1.3 on 2022-11-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0002_pricingplan_created_at_pricingplan_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingplan',
            old_name='plan',
            new_name='dietary_plan',
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
