# Generated by Django 4.1.3 on 2022-12-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0004_alter_pricingplan_options_pricingplan_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['-sort_order'], 'verbose_name': 'Pricing Plan', 'verbose_name_plural': 'Pricing Plans'},
        ),
        migrations.RenameField(
            model_name='pricingplan',
            old_name='order',
            new_name='sort_order',
        ),
    ]
