# Generated by Django 4.1.3 on 2022-11-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meal Option',
                'verbose_name_plural': 'Meal Options',
                'db_table': 'meal_options',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='meal_options',
            field=models.ManyToManyField(to='subscriptions.mealoption'),
        ),
    ]
