# Generated by Django 4.1.3 on 2022-11-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscription_meal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='meal_options',
            field=models.ManyToManyField(to='subscriptions.mealoption'),
        ),
    ]
