# Generated by Django 4.1.3 on 2022-12-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscription_meal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='meals_per_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
