# Generated by Django 4.1.3 on 2022-12-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscription_meals_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='number_of_weeks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
