# Generated by Django 4.1.3 on 2022-11-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('postcode', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=25)),
                ('town', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Postcode',
                'verbose_name_plural': 'Postcodes',
                'db_table': 'postcodes',
            },
        ),
    ]
