# Generated by Django 4.1.3 on 2023-02-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostcodeArea',
            fields=[
                ('postcode', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=25)),
                ('town', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Postcode Area',
                'verbose_name_plural': 'Postcode Areas',
                'db_table': 'postcode_areas',
            },
        ),
    ]
