# Generated by Django 4.1.3 on 2022-11-24 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcode_areas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postcode',
            new_name='PostcodeArea',
        ),
        migrations.AlterModelOptions(
            name='postcodearea',
            options={'verbose_name': 'Postcode Area', 'verbose_name_plural': 'Postcode Areas'},
        ),
        migrations.AlterModelTable(
            name='postcodearea',
            table='postcode_areas',
        ),
    ]
