# Generated by Django 4.1.3 on 2022-11-24 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postcode_areas', '0002_rename_postcode_postcodearea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcodearea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcodearea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
