# Generated by Django 4.1.3 on 2023-02-01 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('dietary_plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, default='', max_length=250)),
                ('days', models.JSONField()),
                ('start_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_type', models.CharField(choices=[('receipt', 'Απόδειξη'), ('invoice', 'Τιμολόγιο')], default='receipt', max_length=30)),
                ('payment_method', models.CharField(choices=[('online', 'Χρεωστική/Πιστωτική κάρτα'), ('physical', 'Αντικαταβολή')], default='online', max_length=30)),
                ('payment_status', models.CharField(choices=[('pending', 'Εκκρεμεί'), ('aborted', 'Ακυρώθηκε'), ('completed', 'Ολοκληρώθηκε')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_coupon', to='coupons.coupon')),
                ('dietary_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_plan', to='dietary_plans.dietaryplan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('landline_phone', models.CharField(blank=True, max_length=15)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('address_number', models.PositiveIntegerField()),
                ('town', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postcode', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping_details', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order - Shipping Details',
                'verbose_name_plural': 'Order - Shipping Details',
                'db_table': 'order_shipping_details',
            },
        ),
        migrations.CreateModel(
            name='OrderCompanyTaxDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VAT', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_activity', models.CharField(max_length=250)),
                ('tax_location', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('address_number', models.PositiveIntegerField()),
                ('town', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postcode', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_company_tax_details', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order - Company Tax Details',
                'verbose_name_plural': 'Order - Company Tax Details',
                'db_table': 'order_company_tax_details',
            },
        ),
        migrations.CreateModel(
            name='OrderBillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('landline_phone', models.CharField(blank=True, max_length=15)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('address_number', models.PositiveIntegerField()),
                ('town', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postcode', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_billing_details', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order - Billing Details',
                'verbose_name_plural': 'Order - Billing Details',
                'db_table': 'order_billing_details',
            },
        ),
    ]
