# Generated by Django 4.1.3 on 2022-12-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Εκκρεμεί'), ('aborted', 'Ακυρώθηκε'), ('completed', 'Ολοκληρώθηκε')], default='', max_length=25),
            preserve_default=False,
        ),
    ]
